### ISSUE TITLE
Updates for 2020 + 2021?

### ISSUE THREAD

**Issue by jfklimek** [zachcmathews/keynotesRTC#3]
Curious if this code is planned to be updated for 2020 or 2021? Is there an easy code fix so that it can apply for those versions of Revit?

**Comment by zachcmathews** [comment]
I just tested in 2021 and it still works! Just download the latest release here:
 https://github.com/zachcmathews/keynotesRTC/releases/tag/v0.2.1

Extract into:
C:\ProgramData\Autodesk\Revit\Addins\2020 for Revit 2020
C:\ProgramData\Autodesk\Revit\Addins\2021 for Revit 2021

Remember to check the unblock checkbox in the DLL properties since this add-in isn't signed. Refer to the following issue for more information:
https://github.com/zachcmathews/LTFilter/issues/2

According to Jeremy Tammik over at The Building Coder: "in general, the Revit API assemblies are upwards compatible, If you create an add-in using the Revit 2012 API assemblies and make no use of Revit 2013 API features, and all the Revit 2012 API features that you do make use of remained unchanged in Revit 2013, then you can load and execute your 2012 add-in in Revit 2013."
https://thebuildingcoder.typepad.com/blog/2012/07/multi-version-add-in.html

This add-in is very minimalistic <50 source code lines and 7 calls to the Revit API, so it's unlikely to need very much maintenance. (Unless Autodesk decides to do away with tab-delimited text files in which case this add-in becomes obsolete.)

**Comment by zachcmathews** [comment]
This repository is being deprecated. Please check out [pyRevitBoost](https://github.com/zachcmathews/pyRevitBoost) to continue collaborating on keynotes. This removes the headache of unblocking the DLL for future Revit versions and provides many more tools to go along with the ability to edit keynotes collaboratively.
